<?php 
require_once('model/message.php');
require_once('model/cours.php');
require_once('model/modelBDD.php');
require_once('config/configBDD.php');
require_once('controller/controlleurInscription.php');
require_once('controller/controlleurConnexion.php');
require_once('controller/controlleurUtilisateur.php');
require_once('controller/controlleurMaillist.php');
require_once('controller/controlleurCours.php');
require_once('controller/controlleurForum.php');
require_once('controller/controlleurContact.php');
require_once('controller/controlleurQCM.php');
require_once('controller/controlleurAdmin.php');
?>